<?xml version="1.0"?>
<package format="3">
  <name>doggo_bringup</name>
  <version>0.1.0</version>
  <description>Top-level launch and configuration for doggo.</description>
  <maintainer email="maintainers@example.com">doggo contributors</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>doggo_gazebo</exec_depend>
  <exec_depend>doggo_perception</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>

